name: ğŸš¨ ESLint
on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout Repo
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.21"

      - name: ğŸ“¦ Install Dependencies
        run: uv sync

      - name: ğŸš¨ Lint
        run: basedpyright
