name: ğŸ§ª Tests
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout Repo
        uses: actions/checkout@v4

      - name: "ğŸ Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: ğŸ”§ Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.7.21"

      - name: "ğŸ‘¾ Create virtual environment"
        run: uv venv

      - name: ğŸ“¦ Install Dependencies
        run: make install

      - name: ğŸ§ª Run Tests
        run: make test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
