name: ğŸ§ª Test Coverage
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout Repo
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.21"

      - name: ğŸ“¦ Install Dependencies
        run: uv sync --frozen

      - name: ğŸ§ª Run Tests
        run: pytest
