name: ğŸ§ª Test Coverage
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.7.21"

      - name: ğŸ“¦ Install Dependencies
        run: uv sync --frozen --dev

      - name: ğŸ§ª Run Tests
        run: uv run pytest
